### ISSUE TITLE
Error: "Expected 4 type arguments, but got 1"

### ISSUE THREAD

**Issue by brentguistwite** [Microsoft/TypeScript-React-Starter#136]
I followed along with all of the steps in the README. After following the steps in "Creating a store" The app fails to compile and provides an error:
"my-app/src/index.tsx
(12,27): Expected 4 type arguments, but got 1."
I cloned the master branch from this repo and compared my code to yours and even went as far as copying/pasting your code over mine to make sure I wasnt missing anything. None of that fixed the error. Please advise

**Comment by creambyemute** [comment]
An update (4.0.0) of Redux was released today, are you by chance already using that? The createStore signature has changed from the last released version 3.7.2.

**Comment by brentguistwite** [comment]
@creambyemute Just looked and I am using 4.0.0. Good catch, thanks for helping out so quickly!

**Comment by etlolap** [comment]
Now I know redux 4.0.0 caused the issue. How can I fix it? How to change the codes at sr/index.tsx?

**Comment by haani104** [comment]
@etlolap  Not sure if this is the solution to it, but this worked for me

I imported `EnthusiasmAction`

```
import { EnthusiasmAction } from './actions/index';
```

and used like below

```
const store = createStore<IStoreState, EnthusiasmAction, any, any>(enthusiam, {
  enthusiasmLevel: 1,
  languageName: 'TypeScript'
});
```

**Comment by Granddevv** [comment]
Thanks very much. I fixed issue quickly.
Maybe it works very well on 'redux': '^3.7.2'.

**Comment by ShawnXiao105** [comment]
@haani104  This does not work for me. Error message as follows: 

` Type declaration of 'any' loses type-safety. Consider replacing it with a more precise type.`

**Comment by woutervanvliet** [comment]
The following also works for me: 

```
const store = createStore<IStoreState, EnthusiasmAction, null, null>(enthusiam, {
  enthusiasmLevel: 1,
  languageName: 'TypeScript'
});
```

Guess I'll have to replace the null's with something as soon as I start to use middleware

**Comment by mehmetnyarar** [comment]
I still get an error: 

```
const initialState: IStoreState = {
  enthusiasmLevel: 100,
  languageName: "TypeScript"
};

const store = createStore<IStoreState, EnthusiasmAction, null, null>(
  enthusiasm,
  initialState,
  null // otherwise preloadedState is ignored
);
```

Error: 

> Argument of type '(state: IStoreState, action: EnthusiasmAction) => IStoreState' is not assignable to parameter of type 'Reducer<IStoreState, EnthusiasmAction>'.
>   Types of parameters 'state' and 'state' are incompatible.
>     Type 'IStoreState | undefined' is not assignable to type 'IStoreState'.
>       Type 'undefined' is not assignable to type 'IStoreState'.

When I hover `createStore`:

> (alias) createStore<IStoreState, EnthusiasmAction, null, null>(reducer: Reducer<IStoreState, EnthusiasmAction>, preloadedState: DeepPartial<IStoreState>, enhancer?: StoreEnhancer<null, {}> | undefined): Store<IStoreState & null, AnyAction> & null (+1 overload)
> import createStore
> 

Signatures:

```
export interface StoreCreator {
  <S, A extends Action, Ext, StateExt>(reducer: Reducer<S, A>, enhancer?: StoreEnhancer<Ext, StateExt>): Store<S & StateExt, A> & Ext;
  <S, A extends Action, Ext, StateExt>(reducer: Reducer<S, A>, preloadedState: DeepPartial<S>, enhancer?: StoreEnhancer<Ext>): Store<S & StateExt> & Ext;
}

```
Dependencies: 

```
"dependencies": {
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-redux": "^5.0.7",
    "react-scripts-ts": "2.16.0",
    "redux": "^4.0.0"
  },
  "devDependencies": {
    "@types/enzyme": "^3.1.10",
    "@types/enzyme-adapter-react-16": "^1.0.2",
    "@types/jest": "^23.1.1",
    "@types/node": "^10.3.4",
    "@types/react": "^16.4.1",
    "@types/react-dom": "^16.0.6",
    "@types/react-redux": "^6.0.2",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "react-addons-test-utils": "^15.6.2",
    "typescript": "^2.9.2"
  }
```

**Comment by nobodyman** [comment]
Why was this issue closed if the tutorial still uses the outdated syntax?

**Comment by sparkydasrath** [comment]
Also following along the tutorial and using v4. I was able to sort out some issues from the suggestions above but now have a final red squiggle in the src/index.tsx file:

`ReactDOM.render(
  <Provider store={store}>
    <Hello />
  </Provider>,
  document.getElementById('root') as HTMLElement
);`

hovering over <Hello /> gives me:

`[ts] Type '{}' is not assignable to type 'IntrinsicAttributes & Props'.
  Type '{}' is not assignable to type 'Props'.
    Property 'name' is missing in type '{}'.`

**Comment by QingNote** [comment]
If don't know what the type is, try to describe it as 'any'
const store = createStore<StoreState,any,any,any>(enthusiasm, {
    enthusiasmLevel: 1,
    languageName: 'TypeScript',
});

**Comment by eberkund** [comment]
@mehmetnyarar did you find a solution? I have the same problem.

**Comment by chvin** [comment]
@eberkund @mehmetnyarar 
back redux version to 3: `tnpm install redux@3 --save`,  and back to guide code(one argument), it running success.
![image](https://user-images.githubusercontent.com/5383506/57914403-2669cd00-78c1-11e9-9e9d-bb1ce34f79e5.png)

**Comment by mehmetnyarar** [comment]
hey guys, @eberkund @chvin 

It's been really a long time and i don't use this boilerplate in my projects anymore. Creating a React/TypeScript project is [very easy now](https://facebook.github.io/create-react-app/docs/adding-typescript) and I don't have any type problem with Redux as well )
